defmodule Piano.Repo.Migrations.AddPrimaryAgentToThreads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:threads) do
      add :primary_agent_id,
          references(:agents, column: :id, name: "threads_primary_agent_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:threads) do
      remove :primary_agent_id
    end

    drop constraint(:threads, "threads_primary_agent_id_fkey")
  end
end