defmodule Piano.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:threads, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:messages, primary_key: false) do
      add :agent_id, references(:agents, column: :id, name: "messages_agent_id_fkey", type: :uuid)

      add :thread_id,
          references(:threads,
            column: :id,
            name: "messages_thread_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :source, :text, null: false
      add :role, :text, null: false
      add :content, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:agents, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :enabled_skills, {:array, :text}, null: false, default: []
      add :enabled_tools, {:array, :text}, null: false, default: []
      add :system_prompt, :text
      add :model, :text, null: false
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:agents)

    drop constraint(:messages, "messages_thread_id_fkey")

    drop constraint(:messages, "messages_agent_id_fkey")

    drop table(:messages)

    drop table(:threads)
  end
end