defmodule Piano.Repo.Migrations.CreateCoreSchemas do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:surfaces, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :app, :text, null: false
      add :identifier, :text, null: false
      add :config, :map, null: false, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end

    create unique_index(:surfaces, [:app, :identifier],
             name: "surfaces_unique_app_identifier_index"
           )

    create table(:agents_v2, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :model, :text, null: false
      add :workspace_path, :text, null: false
      add :sandbox_policy, :text, null: false
      add :auto_approve_policy, :text, null: false
      add :is_default, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end

    create table(:threads_v2, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :codex_thread_id, :text
      add :reply_to, :text, null: false
      add :status, :text, null: false, default: "active"
      add :agent_id, references(:agents_v2, column: :id, name: "threads_v2_agent_id_fkey", type: :uuid)
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end

    create table(:interactions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :codex_turn_id, :text
      add :original_message, :text, null: false
      add :reply_to, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :response, :text
      add :thread_id, references(:threads_v2, column: :id, name: "interactions_thread_id_fkey", type: :uuid)
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end

    create table(:interaction_items, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :codex_item_id, :text, null: false
      add :type, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :status, :text, null: false, default: "started"
      add :interaction_id, references(:interactions, column: :id, name: "interaction_items_interaction_id_fkey", type: :uuid), null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end
  end

  def down do
    drop table(:interaction_items)
    drop table(:interactions)
    drop table(:threads_v2)
    drop table(:agents_v2)
    drop_if_exists unique_index(:surfaces, [:app, :identifier], name: "surfaces_unique_app_identifier_index")
    drop table(:surfaces)
  end
end
