defmodule Piano.Repo.Migrations.ImagePaths do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:interactions) do
      add :image_paths, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:interactions) do
      remove :image_paths
    end
  end
end