defmodule Piano.Repo.Migrations.AddTelegramSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:telegram_sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :agent_id,
          references(:agents, column: :id, name: "telegram_sessions_agent_id_fkey", type: :uuid)

      add :thread_id,
          references(:threads,
            column: :id,
            name: "telegram_sessions_thread_id_fkey",
            type: :uuid
          ), null: false

      add :chat_id, :bigint, null: false, primary_key: true
    end

    create unique_index(:telegram_sessions, [:chat_id],
             name: "telegram_sessions_unique_chat_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:telegram_sessions, [:chat_id],
                     name: "telegram_sessions_unique_chat_id_index"
                   )

    drop constraint(:telegram_sessions, "telegram_sessions_thread_id_fkey")

    drop constraint(:telegram_sessions, "telegram_sessions_agent_id_fkey")

    drop table(:telegram_sessions)
  end
end