defmodule Piano.Repo.Migrations.AddUsersAndSurfaces do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_surfaces, primary_key: false) do
      add :surface_id,
          references(:surfaces, column: :id, name: "users_surfaces_surface_id_fkey", type: :uuid),
          null: false

      add :user_id,
          references(:users, column: :id, name: "users_surfaces_user_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :joined_at, :utc_datetime_usec, null: false
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:users, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :username, :text
      add :display_name, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users_surfaces, [:user_id, :surface_id],
             name: "users_surfaces_unique_user_surface_index"
           )

    alter table(:threads_v2) do
      add :surface_id,
          references(:surfaces, column: :id, name: "threads_v2_surface_id_fkey", type: :uuid)
    end

    alter table(:surfaces) do
      add :single_user?, :boolean, null: false
    end
  end

  def down do
    alter table(:surfaces) do
      remove :single_user?
    end

    alter table(:threads_v2) do
      remove :surface_id
    end

    drop constraint(:threads_v2, "threads_v2_surface_id_fkey")

    drop_if_exists unique_index(:users_surfaces, [:user_id, :surface_id],
                     name: "users_surfaces_unique_user_surface_index"
                   )

    drop table(:users)

    drop constraint(:users_surfaces, "users_surfaces_user_id_fkey")

    drop constraint(:users_surfaces, "users_surfaces_surface_id_fkey")

    drop table(:users_surfaces)
  end
end