defmodule Piano.Repo.Migrations.AddForkingToThreads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:threads) do
      add :forked_from_thread_id, :uuid
      add :forked_from_message_id, :uuid
    end
  end

  def down do
    alter table(:threads) do
      remove :forked_from_message_id
      remove :forked_from_thread_id
    end
  end
end